server.port=8080

spring.data.mongodb.uri=mongodb+srv://dhruvihegde7999_db_user:9sRhO8qMJGhDC2by@cluster0.esjzax0.mongodb.net/AttendanceSystem?appName=Cluster0

jwt.secret=dhruvi-very-secure-key-1234567890
jwt.expiration=86400000

cors.allowed-origins=http://localhost:5173

logging.level.com.attendx=DEBUG
logging.level.org.springframework.security=WARN